# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

version: '3'

services:
  strapi:
    container_name: strapi
    image: strapi/strapi:latest
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=secret
    ports:
      - 1337:1337
    volumes:
      - ../cms/app:/srv/app
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql:8.0.18
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: strapi
    volumes:
      - ../cms/db:/var/lib/mysql
